[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
minicircuit_commands = { path = "../minicircuit/commands" }
minicircuit_driver = { path = "../minicircuit/driver" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
