[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
minicircuit = { path = "../minicircuit" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
